"""Stable public API for the AIWire v1 protocol.

Applications should import AIWire protocol types and helpers from this module.
The historical :mod:`aura_compression` root exports remain available for
backwards compatibility, but they also contain experimental research APIs.
"""

from ..ai_wire import (
    AI_WIRE_COMPATIBILITY_MANIFEST_SCHEMA,
    AI_WIRE_CONTROL_LUT_SCHEMA,
    AI_WIRE_DEFAULT_LEVEL,
    AI_WIRE_DEFAULT_SESSION_TEMPLATE_CATALOG_VERSION,
    AI_WIRE_DICTIONARY_EXTENSION_SCHEMA,
    AI_WIRE_DICTIONARY_FNV1A64,
    AI_WIRE_DICTIONARY_SHA256,
    AI_WIRE_FALLBACK_CODECS,
    AI_WIRE_HANDSHAKE_SCHEMA,
    AI_WIRE_MISSION_CRITICAL,
    AI_WIRE_MISSION_CRITICAL_CONTROL_TYPES,
    AI_WIRE_NARY_NEGOTIATION_SCHEMA,
    AI_WIRE_NEGOTIATION_SCHEMA,
    AI_WIRE_PROTOCOL,
    AI_WIRE_SESSION_DICTIONARY_ACK_SCHEMA,
    AI_WIRE_SESSION_DICTIONARY_DIFF_SCHEMA,
    AI_WIRE_SESSION_DICTIONARY_STATE_SCHEMA,
    AI_WIRE_SESSION_RESUME_HELLO_SCHEMA,
    AI_WIRE_SESSION_RESUME_RESPONSE_SCHEMA,
    AI_WIRE_SESSION_TEMPLATE_CATALOG_SCHEMA,
    AI_WIRE_SESSION_TEMPLATE_UPDATE_SCHEMA,
    AI_WIRE_STATIC_DICTIONARY,
    AI_WIRE_STATIC_DICTIONARY_CATALOG_SCHEMA,
    AI_WIRE_STATIC_DICTIONARY_VERSION,
    AI_WIRE_SUPPORTED_VERSIONS,
    AI_WIRE_SYSTEM_CONTROL_SCHEMA,
    AI_WIRE_VERSION,
    AIWireCompatibilityCheck,
    AIWireCompatibilityManifest,
    AIWireControlLUTEntry,
    AIWireControlLUTFrame,
    AIWireDictionaryExtension,
    AIWireFallbackError,
    AIWireFrame,
    AIWireFrameError,
    AIWireHandshake,
    AIWireHandshakeError,
    AIWireNaryNegotiation,
    AIWireNativeError,
    AIWireNativeStatus,
    AIWireNegotiation,
    AIWireSessionDecoder,
    AIWireSessionDictionaryAck,
    AIWireSessionDictionaryDiff,
    AIWireSessionEncoder,
    AIWireSessionResumeHello,
    AIWireSessionResumeResponse,
    AIWireSessionTemplates,
    AIWireSessionTemplateUpdate,
    AIWireStats,
    AIWireSystemControlMessage,
    aiwire_compatibility_manifest_sha256,
    aiwire_control_lut_frame_hex,
    aiwire_control_lut_sha256,
    aiwire_dictionary_extensions_sha256,
    aiwire_native_status,
    aiwire_session_dictionary_state_sha256,
    aiwire_session_template_catalog_sha256,
    aiwire_session_templates_sha256,
    aiwire_static_dictionary_catalog_sha256,
    apply_aiwire_session_dictionary_diff,
    apply_aiwire_session_template_update,
    build_aiwire_compatibility_manifest,
    build_aiwire_dictionary_extension,
    build_aiwire_handshake,
    build_aiwire_session_dictionary_diff,
    build_aiwire_session_resume_hello,
    build_aiwire_session_template_catalog,
    build_aiwire_session_template_update,
    build_aiwire_static_dictionary_catalog,
    build_aiwire_system_control_message,
    compress_ai_wire_frames,
    decode_ai_wire_message,
    decode_aiwire_control_lut_frame,
    decode_aiwire_fallback_frame,
    decompress_ai_wire_frames,
    discover_ai_wire_session_templates,
    encode_ai_wire_message,
    encode_aiwire_control_lut_frame,
    encode_aiwire_fallback_frame,
    negotiate_aiwire_handshake,
    negotiate_aiwire_nary_handshake,
    negotiate_aiwire_session_resume,
    normalize_aiwire_control_lut,
    normalize_aiwire_dictionary_extensions,
    normalize_aiwire_session_templates,
    verify_aiwire_compatibility_manifest,
    verify_aiwire_session_dictionary_ack,
    verify_aiwire_session_resume_response,
    verify_aiwire_system_control_message,
)
from ..aiwire_resume_cache import (
    AI_WIRE_RESUME_CACHE_ENTRY_SCHEMA,
    AI_WIRE_RESUME_CACHE_ENV,
    AI_WIRE_RESUME_CACHE_SCHEMA,
    AIWireResumeCache,
    AIWireResumeCacheEntry,
    default_aiwire_resume_cache_path,
)

AIWIRE_PUBLIC_API_VERSION = 1
"""Version of this Python import contract, independent of wire versioning."""

__all__ = [name for name in globals() if name.startswith(("AIWire", "AI_WIRE", "aiwire_"))]
__all__ += [
    "AIWIRE_PUBLIC_API_VERSION",
    "apply_aiwire_session_dictionary_diff",
    "apply_aiwire_session_template_update",
    "build_aiwire_compatibility_manifest",
    "build_aiwire_dictionary_extension",
    "build_aiwire_handshake",
    "build_aiwire_session_dictionary_diff",
    "build_aiwire_session_resume_hello",
    "build_aiwire_session_template_catalog",
    "build_aiwire_session_template_update",
    "build_aiwire_static_dictionary_catalog",
    "build_aiwire_system_control_message",
    "compress_ai_wire_frames",
    "decode_ai_wire_message",
    "decode_aiwire_control_lut_frame",
    "decode_aiwire_fallback_frame",
    "decompress_ai_wire_frames",
    "discover_ai_wire_session_templates",
    "encode_ai_wire_message",
    "encode_aiwire_control_lut_frame",
    "encode_aiwire_fallback_frame",
    "negotiate_aiwire_handshake",
    "negotiate_aiwire_nary_handshake",
    "negotiate_aiwire_session_resume",
    "normalize_aiwire_control_lut",
    "normalize_aiwire_dictionary_extensions",
    "normalize_aiwire_session_templates",
    "verify_aiwire_compatibility_manifest",
    "verify_aiwire_session_dictionary_ack",
    "verify_aiwire_session_resume_response",
    "verify_aiwire_system_control_message",
]
__all__ = sorted(set(__all__))
