/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS - modified to only use local Linux binaries */

const { platform, arch } = process

let nativeBinding = null
let loadError = null

switch (platform) {
  case 'linux':
    if (arch === 'x64') {
      try {
        nativeBinding = require('./aura-native.linux-x64-gnu.node')
      } catch (e) {
        loadError = e
      }
    } else if (arch === 'arm64') {
      try {
        nativeBinding = require('./aura-native.linux-arm64-gnu.node')
      } catch (e) {
        loadError = e
      }
    } else {
      throw new Error(`Unsupported Linux architecture: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported platform: ${platform}. Currently only Linux x64 and ARM64 are supported.`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding for ${platform}-${arch}`)
}

const { CompressionMethod, AuraCompressor } = nativeBinding

module.exports.CompressionMethod = CompressionMethod
module.exports.AuraCompressor = AuraCompressor
